### ISSUE TITLE
The path that depends on the specific computer

### ISSUE THREAD

**Issue by serega404** [p6laris/MorseSharp#10]
I am not versed in publishing nuget packages, but this line does not allow me to assemble a solution
```xml
<None Include="..\..\..\..\OneDrive\Desktop\MorseSharp.png">
```
I replaced the path with `..\MorseSharp.png` and the build is working

File: [MorseSharp.csproj](https://github.com/p6laris/MorseSharp/blob/master/MorseSharp/MorseSharp.csproj)

**Comment by p6laris** [comment]
Thank you for bringing this to the attention, it seems that i used relative path to the logo that caused the problem.
