### ISSUE TITLE
! character

### ISSUE THREAD

**Issue by lorenblue** [p6laris/MorseSharp#31]
Hello again, 

I see that most special characters are covered, but oddly there doesn't seem to be a morse equivalent for '!' in your package.

I also have two related questions:

1. What is your source for the morse code translations? I trust that they're accurate, but it would still be helpful to see the source.
2. Could the word (character?) not presented exception make it easier to grab the character that failed to be translated? 

Cheers thanks.

**Comment by p6laris** [comment]
Welcome back again!

The Morse code translations for all languages, except Kurdish, KurdishLatin and Russian, were sourced from the [website](https://morsedecoder.com/).  I'll make sure to comment out this information in the code too.

Could you please elaborate on the specific use cases you have in mind for the (CharacterNotPresentedException I've no idea why i wrote it as WORD 😁 btw)? Currently, the exception message provides clear information about the failed translated characters. Nevertheless, if you have any specific scenarios or improvements in mind, I'm open to discussing them. Additionally, I'll be adding all punctuations, including '!' and double check it from the mentioned website.

Thank you once again for your valuable feedback. Please feel free to share any further suggestions or contributions you might have.

**Comment by lorenblue** [comment]
I would like to format an appropriate error message to pass through to the user (I'm using this package as part of a discord bot). It would be easy for me to parse through the error message and get the failing character and language, but it would be even _easier_ to have those be properties on the exception itself. No idea if that follows best practices, but it seems to make sense to me. All good either way though!

**Comment by p6laris** [comment]
Wow, I definitely want to check out that bot!

Regarding your suggestion, I don't see it as bad practice at all. In fact, I also think exposing a pair of properties in the exception sounds like a great idea. I'll work on implementing it soon. If you have any more ideas or run into issues, feel free to let me know. 

Happy coding!
