### ISSUE TITLE
Pangrams in unit tests

### ISSUE THREAD

**Issue by serega404** [p6laris/MorseSharp#9]
I suggest using pangrams for unit tests. This will allow you to check all the letters from the given language.

Exaples: https://en.wikipedia.org/wiki/Pangram#Short_pangrams

**Comment by serega404** [comment]
I also think it's worth clarifying which languages are supported, this is the first thing I was looking for when I saw your library.

**Comment by p6laris** [comment]
Thanks for your suggestion! Using pangrams in unit tests can indeed be a valuable practice for thoroughly checking language-specific functionality, apologize for any confusion i will add supported languages.
